spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:employees
    username: admin
    password: admin

springdoc:
  swagger-ui:
    path: swagger-ui.html